# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  test-master-up-to-date:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run:
          name: Echo env
          command: env

workflows:
  test-master-up-to-date:
    jobs:
      - test-master-up-to-date

